lines = [
    "import sys, json",
    "sys.path.insert(0, '.')",
    "",
    "print('=== Phase 3: Strategy Engine Final Test ===\n')",
    "",
    "from elfa_grvt_bot.scorer import fetch_market_snapshot, compute_scores, calc_trade_params",
    "",
    "print('[Test 1] Fetching live market snapshot...')",
    "snap = fetch_market_snapshot('BTCUSDT')",
    "price = snap.get('price') or 0.0",
    "print('  Price:        USD ' + f'{price:,.1f}')",
    "print('  ST_4H:        ' + str(snap.get('supertrend_4h')))",
    "print('  ST_1H:        ' + str(snap.get('supertrend_1h')))",
    "print('  EMA50_4H:     ' + f\"{snap.get('ema50_4h') or 0:,.1f}\")",
    "print('  EMA200_4H:    ' + f\"{snap.get('ema200_4h') or 0:,.1f}\")",
    "print('  ADX_4H:       ' + f\"{snap.get('adx_4h') or 0:.1f}\")",
    "print('  DI+:          ' + f\"{snap.get('di_plus_4h') or 0:.1f}\" + '  DI-: ' + f\"{snap.get('di_minus_4h') or 0:.1f}\")",
    "print('  RSI_1H:       ' + f\"{snap.get('rsi_1h') or 50:.1f}\")",
    "print('  RSI_15m:      ' + f\"{snap.get('rsi_15m') or 50:.1f}\")",
    "print('  VWAP_1H:      ' + f\"{snap.get('vwap_1h') or 0:,.1f}\")",
    "print('  VolRatio_15m: ' + f\"{snap.get('vol_ratio_15m') or 1:.2f}\" + 'x')",
    "print('  Funding:      ' + f\"{snap.get('funding_rate') or 0:.5f}\")",
    "print('  Spread:       ' + f\"{snap.get('spread') or 0:.2f}\")",
    "print('  Errors:       ' + str(snap.get('errors') or 'None'))",
    "assert price > 0, f'price={price}'",
    "print('  [PASS] price=' + str(price) + '\n')",
    "",
    "print('[Test 2] Scores...')",
    "ls, ss, mode = compute_scores(snap)",
    "print('  Long=' + str(ls) + '  Short=' + str(ss) + '  Mode=' + mode)",
    "assert mode in ('BULL_TREND','BEAR_TREND','LONG_REVERSAL','SHORT_REVERSAL','RANGE')",
    "print('  [PASS]\n')",
    "",
    "print('[Test 3] Trade params...')",
    "side = 'long' if ls >= ss else 'short'",
    "p = calc_trade_params(side, price, snap, ls, ss, 1132.0, mode)",
    "if p:",
    "    print('  Side=' + side + '  Entry=USD ' + f\"{p['entry_price']:,.1f}\" + '  SL=USD ' + f\"{p['stop_loss']:,.1f}\" + '  TP=USD ' + f\"{p['take_profit']:,.1f}\")",
    "    print('  RR=' + str(p['rr']) + '  Risk=USD ' + f\"{p['risk_usdt']:.2f}\" + '(' + f\"{p['risk_pct']*100:.2f}\" + '%)  Qty=' + str(p['qty_btc']) + 'BTC  Lev=' + str(p['effective_leverage']) + 'x')",
    "    print('  [PASS]\n')",
    "else:",
    "    print('  [INFO] calc returned None - HOLD condition\n')",
    "",
    "print('[Test 4] Full evaluate()...')",
    "from elfa_grvt_bot.strategy_engine import evaluate",
    "test_cases = [",
    "    ('d9067784-75a5-4953-ba9c-29a0cbfee5aa', 'SHORT_SETUP_15m'),",
    "    ('30d4435d-e933-446f-9162-ca98c4afca03', 'BEAR_FILTER_SHORT'),",
    "    ('f7667ea4-85f2-4d10-a534-5bf1a67272d3', 'BULL_FILTER_LONG'),",
    "]",
    "for qid, role in test_cases:",
    "    r = evaluate(qid, account_equity=1132.0)",
    "    print('  [' + role + '] Action=' + r['action'] + ' L=' + str(r['long_score']) + ' S=' + str(r['short_score']) + ' Mode=' + r['mode'])",
    "    if r['action'] != 'HOLD':",
    "        ep = r.get('entry_price') or 0",
    "        sl = r.get('stop_loss') or 0",
    "        tp = r.get('take_profit') or 0",
    "        print('    Entry=USD ' + f'{ep:,.1f}' + '  SL=USD ' + f'{sl:,.1f}' + '  TP=USD ' + f'{tp:,.1f}')",
    "        print('    Qty=' + str(r.get('qty_btc')) + 'BTC  RR=' + str(r.get('rr')) + '  Lev=' + str(r.get('effective_leverage')) + 'x')",
    "print('  [PASS]\n')",
    "",
    "print('=== ALL TESTS PASSED - Bot is ready ===' )",
]

with open('test_engine.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print('write_test.py: test_engine.py written OK')